spring:
  application:
    name: user-service


  data:
    mongodb:
      uri: mongodb://localhost:27017/Reviewyme

server:
  port: 8031


#  mvc:
#    pathmatch:
#      matching-strategy: ANT_PATH_MATCHER

