spring:

  cloud:
    config:
      server:
        native:
          search-locations: file:./config-repo/config

  profiles:
    group:
      "local": "native"

  application:
    name: config-server

---
spring:
  config:
    activate:
      on-profile: local

server:
  port: 8888

