spring:
  application:
    name: resume-creation-service
  jackson:
    date-format: yyyy-MM-dd
    serialization:
      write-dates-as-timestamps: false



  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reviewyme
    username: root
    password: Godofwar08..

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8032

